services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432' # Левая часть - порт хоста, правая - контейнера
    volumes:
      # Сохраняем данные БД, чтобы они не пропадали при перезапуске
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: backend # Указываем папку, где лежит Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      # Имя хоста должно совпадать с именем сервиса выше (postgres)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update # Чтобы таблицы создались автоматически
    restart: on-failure

  frontend:
      build:
        context: frontend # Указываем папку, где лежит Dockerfile
      depends_on:
        - backend
      ports:
        - "8090:80"
      restart: on-failure

volumes:
  postgres_data: